# Generated by Django 2.2.16 on 2020-09-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_id', models.IntegerField()),
                ('smiles', models.TextField(help_text='Enter the SMILES', max_length=1000)),
                ('molecular_weight', models.FloatField()),
                ('ALogP', models.FloatField()),
                ('molecular_formula', models.CharField(help_text='Enter the molecular formula', max_length=100)),
                ('num_rings', models.IntegerField()),
                ('image', models.CharField(help_text='Enter the image path', max_length=1000)),
                ('assay_results', models.TextField(default='', help_text='Enter the assay results', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AssayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('target', models.TextField(help_text='Enter the protein target', max_length=100)),
                ('result', models.TextField(help_text='Enter the type of result', max_length=100)),
                ('operator', models.TextField(help_text='Enter the operator', max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.TextField(help_text='Enter the units of the result', max_length=100)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_catalogue_app.Compound')),
            ],
        ),
    ]
