# Generated by Django 2.2.16 on 2020-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_catalogue_app', '0003_auto_20200908_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayresult',
            name='operator',
            field=models.CharField(help_text='Enter the operator', max_length=100),
        ),
        migrations.AlterField(
            model_name='assayresult',
            name='result',
            field=models.CharField(help_text='Enter the type of result', max_length=100),
        ),
        migrations.AlterField(
            model_name='assayresult',
            name='unit',
            field=models.CharField(help_text='Enter the units of the result', max_length=100),
        ),
    ]
