# Generated by Django 2.2.16 on 2020-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_catalogue_app', '0005_remove_compound_assay_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='ALogP',
            field=models.FloatField(verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='compound_id',
            field=models.IntegerField(verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='image',
            field=models.CharField(help_text='Enter the image path', max_length=1000, verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_formula',
            field=models.CharField(help_text='Enter the molecular formula', max_length=100, verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.FloatField(verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='num_rings',
            field=models.IntegerField(verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.TextField(help_text='Enter the SMILES', max_length=1000, verbose_name='SMILES'),
        ),
    ]
